site_name: skoving
site_url: https://skoveit.github.io/skoving/

copyright: ""

extra:
  generator: false
  analytics:
    provider: google
    property: G-QTX3WF018B


theme:
  name: material
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
#   - Home: index.md

  - SkoveNet:
      - Overview: projects/skovenet/index.md

      - Tutorials:
          - Getting Started: projects/skovenet/tutorials/getting-started.md
          - Agent Generation: projects/skovenet/tutorials/agent-generation.md
          - Mission Execution: projects/skovenet/tutorials/mission-execution.md
          - Troubleshooting: projects/skovenet/tutorials/troubleshooting.md

      - Reference:
          - Architecture:
              - Overview: projects/skovenet/reference/architecture/overview.md
              - Networking: projects/skovenet/reference/architecture/networking.md
              - Security: projects/skovenet/reference/architecture/security.md

          - Features:
              - Discovery: projects/skovenet/reference/features/discovery.md
              - Commands: projects/skovenet/reference/features/commands.md

          - Development:
              - Adding Commands: projects/skovenet/reference/development/adding-commands.md

          - Roadmap: projects/skovenet/reference/roadmap.md
          - Why SkoveNet: projects/skovenet/why.md

          

  - Writeups:
      - Overview: writeups/index.md
      - C2: 
          - Sliver - Uno Reverse: writeups/C2/Sliver-UnoReverse.md
      - Web:
          - FTPbox Hardcoded Credentials: writeups/web/FTPbox.md
          - JavaScript Recon to PII Exposure: writeups/web/PII-discl.md
      - Maldev:
          - Payload Hiding: writeups/maldev/payload-Hiding.md


  - Notes:
      - Overview: notes/index.md

      - Windows Internals:
          - DLL: notes/windows internals/DLL.md
          - PE Structure: notes/windows internals/PE structure.md
          - Processes: notes/windows internals/process.md
          - Security: notes/windows internals/security.md
          - Memory:
              - Memory Mapping: notes/windows internals/memory/memory mapping.md

      - Active Directory:
          - Certificate Services: notes/active directory/Certificate Services.md
          - Kerberos: notes/active directory/Kerbros.md
          - LAPS: notes/active directory/LAPS.md
      - Red Team:
          - Proxying: notes/red/proxying.md
          - Windows:
              - Active Directory Techniques: notes/red/windows/Active directory techniques.md
              - Initial Access (0%):
                  - AD Enumeration: notes/red/windows/0%/AD-enum.md
                  - Zero: notes/red/windows/0%/Zero.md
                  - Send Payload: notes/red/windows/0%/send payload.md
              - Foothold (10%): 
                  - Foothold: notes/red/windows/10%/foothold.md
              - Post Exploitation (70%):
                  - Enumeration: notes/red/windows/70%/Enum.md
                  - Exfiltration: notes/red/windows/70%/ExFil.md
                  - Privilege Escalation: notes/red/windows/70%/PrivEsc.md
                  - Lateral Movement: notes/red/windows/70%/Leteral Movement/Leteral Movement.md
                  - OPSEC: notes/red/windows/70%/OPSEC/OPSEC.md
                  - Persistence:
                      - AD Persistence: notes/red/windows/70%/persistence/AD persistance.md
                      - General Persistence: notes/red/windows/70%/persistence/persistence.md
      - Web Security:
          - CSRF: notes/web/CSRF.md
          - GraphQL: notes/web/GraphQL.md
          - HTTP Request Smuggling: notes/web/HTTP request smuggling.md
          - JWT: notes/web/JWT.md
          - Logic Flaws: notes/web/Logic-flaws.md
          - Race Condition: notes/web/Race Condition.md
          - WebSocket: notes/web/WebSocket.md

          
#   - Research: research/index.md
